Phonebook.JaegerByte
TheCSharpAcademy/CodeReviews.Console.Phonebook pull request #46
Opened 2024-03-29 17:33 UTC by JaegerByte

My version of the Phonebook. Any tips or feedback would be greatly appreciated.
Thank you for the opportunity!

2024-04-06 22:56 UTC, TheCSharpAcademy commented
@VocalNight Any updates on this one? 🤓

2024-04-07 18:29 UTC, JaegerByte commented
> @VocalNight Any updates on this one? 🤓

No updates from me :D

2024-04-08 03:21 UTC, VocalNight commented
Uh, did the review i made didn't get posted? One second, sorry about that.

2024-04-08 03:22 UTC, VocalNight requested changes

2024-04-10 20:11 UTC, VocalNight commented on Phonebook.JaegerByte/InputValidationService.cs
> +                    input.All(Char.IsDigit) &&
@JaegerByte Can you confirm if you can see the review now? Sorry for the delay man.

2024-04-14 18:59 UTC, TheCSharpAcademy commented
@JaegerByte Let us know if you need help 🤓

2024-05-22 09:22 UTC, TheCSharpAcademy commented
@JaegerByte We're closing the PR for admin purposes. Feel free to reopen it and resubmit in the academy when you're ready. @VocalNight Let me know if you don't get the points, as this function is new 😊

2024-05-22 09:22 UTC, closed without merging