Finished project
TheCSharpAcademy/CodeReviews.Console.Phonebook pull request #8
Opened 2023-06-11 21:27 UTC by VocalNight

2023-06-24 23:16 UTC, TheCSharpAcademy reviewed
@VocalNight Looks like this project follows is a "database-first" approach with entity framework, could you please provide the sql script for the creation of the database schema?

2023-06-24 23:16 UTC, TheCSharpAcademy commented on PhoneBook.Vocalnight/PhoneBook.Vocalnight/PhoneBook.Vocalnight.csproj
> +
@VocalNight The project won't build because the csproj doesn't have the nuget packages. Could you please update it?

2023-06-24 23:17 UTC, TheCSharpAcademy requested changes
See comments

2023-06-26 02:35 UTC, VocalNight commented
That's strange. I re added the nuggets, should have done the trick now.

I'm also attaching the script to create the database, but that's also werid, it should have been created automatically.
You might need to change the file name from .txt to .sql

[script.txt](https://github.com/TheCSharpAcademy/CodeReviews.Console.Phonebook/files/11862527/script.txt)

2023-06-26 03:34 UTC, TheCSharpAcademy commented
> That's strange. I re added the nuggets, should have done the trick now.
> 
> I'm also attaching the script to create the database, but that's also werid, it should have been created automatically. You might need to change the file name from .txt to .sql
> 
> [script.txt](https://github.com/TheCSharpAcademy/CodeReviews.Console.Phonebook/files/11862527/script.txt)

I see you have this code: 
![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.Phonebook/assets/108711476/9d536041-00d8-4594-99ee-7278c5ee2eeb)
However this method will update (or create) the database based on whatever migrations are in the project. However there are no migrations check into the repository. Maybe you left them out?

2023-06-26 04:41 UTC, VocalNight commented
No, all the files are the ones i uploaded
![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.Phonebook/assets/12613508/f59211d8-48b9-46d3-a5e7-7b569f23463a)

I will change Migrate() to EnsureCreated().

2023-06-28 03:10 UTC, merged